# Generated by Django 5.2.10 on 2026-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_quantitiy_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='craated_at',
            new_name='created_at',
        ),
    ]
